import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./header";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* <About />
        <Menu />
        <Contact /> */}
        <main className="min-h-screen" style={mainStyle}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

const mainStyle: React.CSSProperties = {
  marginTop: "60px",
  height: "80vh",
  minHeight: "80.6vh",
  marginLeft: "5px",
  marginRight: "5px",
};
